package.json
src/extension.ts
src/managers/PluginDataManager.ts
src/managers/TrackerManager.ts

the focused, unfocused may be called while we're initializing the timeCounter.json. this logic uses an initialized flag to let the instance methods to skip that logic if it's not ready.
I was able to reproduce getting a null "this.stats" by quickly toggling the editor focus

added logic to wait until stats are initialized

---

package.json
src/DataController.ts
src/command-helper.ts
src/menu/ProjectCommitManager.ts

this logic swaps the menu flow for the project summary button in the tree view menu
It will show all of the users projects first then show the date range 2nd. I've also added a menu option to show the past 90 days as well as the previous flow helped show the projects that were available for the selected date range.

show projects first in project summary flow

---

package.json
src/command-helper.ts
src/extension.ts
src/managers/KpmManager.ts
src/managers/PluginDataManager.ts
src/model/KeystrokeStats.ts

the previous logic was setting the elapsed code time seconds to zero before setting it into the payload, this fixes that
it also updates the logic in setting the "unfocused" timestamp after the payload is processed as the payload is now processed when the editor is unfocused, or from the 1 minute trigger, or when the editor is deactivated. The 1 minute trigger will not update the unfocused timestamp though.

update logic to set elapsed code time seconds

---

package.json
src/DataController.ts
src/Util.ts
src/managers/KpmManager.ts
src/managers/TrackerManager.ts
src/menu/AccountManager.ts
src/model/models.ts
src/repo/KpmRepoManager.ts
yarn.lock

multi vscode window have their own cache which can mean the tracker manager may end up sending an incorrect jwt based on if the user onboards or switches accounts.
the testing to fetch the jwt out of the file showed it wasn't taking more than 1 to 2 milliseconds

fixed multi win jwt usage

---

src/command-helper.ts
src/tree/KpmProviderManager.ts

we no longer need the currentKeystrokes object since we update the sessionSeconds and other current metrics after every payload completion. WSL works great but there were unhandled rejection exceptions happening preventing the tree from updating

tree metrics value fix

---

package.json
src/DataController.ts

the "showToday" works for the current codemetrics backend, requesting it to build the today and top header section. this was set to false in the past to make the generation of this as fast as possible
https://www.loom.com/share/cbc8fdacf18346e9a35b8205bc2ce760?from_recorder=1

Omit local today

---

package.json
src/DataController.ts
src/menu/ProjectCommitManager.ts
src/user/OnboardManager.ts

This prevents a secondary window from making the decision in nulling the session.json JWT as it may still have the app jwt when the secondary windows initialize.
Normal flow
- install or vscode window loads
- check if there's a JWT, if not we'll create an anon user with an App JWT that we'll first fetch from the backend API
Secondary windows go through this same process, so we should prevent the secondary window from checking if the JWT is an app JWT as the primary may be in the middle of creating the Anon user, which can then lead to creating duplicate users.

check if window is primary before checking appjwt to prevent dup user creation

---

package.json
src/DataController.ts
src/extension.ts
src/managers/PluginDataManager.ts
src/managers/SummaryManager.ts
src/managers/WallClockManager.ts
src/model/models.ts
src/storage/SessionSummaryData.ts
src/storage/TimeSummaryData.ts
src/tree/KpmProvider.ts
src/tree/KpmProviderManager.ts

This swaps out the /sessions/summary with the /metrics/averages api which will only fetch the averages needed for the tree.
The only time this API will now be called is when the tree is opened and the tree updated date is new.

Use metrics api

---

src/DataController.ts
src/Util.ts
src/command-helper.ts
src/managers/SlackManager.ts
src/menu/AccountManager.ts
src/tree/KpmProviderManager.ts

* "Exit full screen" and "Enter full screen" updates
* added actual average in description and more info in the tooltip
* added logic to show the signup flow if clicking on the software.com item if not logged on yet
* fixed the slack disconnect option from the command palette

tree metrics updates and slack disconnect command updates

---

src/Constants.ts
src/Util.ts

- This will allow changing the default software directory so that
in local development we can use a different directory than the
prod plugin.

Add SOFTWARE_DIRECTORY constant

---

src/managers/SlackManager.ts

removes the success and refresh commands from the for loop

show the success and refresh the tree once after updating workspaces

---

src/repo/GitUtil.ts

- HEAD ref can become broken when the default branch is changed from
master to head for example.

Check that HEAD branch actually exists

---

src/repo/GitUtil.ts

- Branch list has preceding space, so trim() it

git command that returns fatal returns null

---

src/repo/GitUtil.ts

- When a range is omitted, it will implicitly use HEAD to compare

Use a commit range when doing git diff

---

src/managers/SlackManager.ts

* this is currently working since there are no other types of integrations, but will break once we add more. this is to future proof this logic

use general integrations fetch to filter out single item and resync

---

README.md

- Removed CloudFront urls for new assets.software.com urls to simplify how we reference our assets
- Tweaked language around the flow section to specifically call out Flow Mode

switch assets to new subdomain

---

src/Util.ts

* when a user is switching accounts we don't want the backend matching them against one of their previously existing users using the plugin uuid or token. It should be match using the oauthId or email.

send plugin uuid and token only when registering

---

src/managers/SlackManager.ts

The slack integration now supports more features, so we need to pass in a target feature flag.

pass slack as an upgrade feature

---

package.json
src/managers/PluginDataManager.ts
src/repo/GitUtil.ts
src/repo/KpmRepoManager.ts

* this caches the default branch git result for 1 day
* and removes git commands that populate the unused outgoing payload attributes
Tested with a hardcoded branch on a known debug project with a 10 second interval. The branch is cached and is used from the cache on the next fetch

cache the default branch git result and cleanup

---

src/extension.ts
src/managers/SyncManger.ts

After testing the secondary vscode windows "status bar metrics" will not update since the current stats update event will be handled by the primary window. This will keep all windows in sync every 10 minutes by updating the status bar with the local session summary file that is updated from that event.

sync secondary vscode windows

---

src/managers/SyncManger.ts
src/user/OnboardManager.ts

the plugin will throw an alert on install if node fs.watch fails to find a file to listen to. this will create the file if it doesn't exist

handle new install when initializing file watch

---

src/DataController.ts
src/app/views/components/account.tsx

This removes the auth type icon (google, github, email) to help alleviate account switching confusion.

remove auth type icon and allow session update

---

src/websockets.ts

The client will parse the ping buffer and use the provided timeout to set its own reconnect timeout + 1 minute

adapt to the server timeout or use default reconnect timeout

---

src/websockets.ts

In case codemetrics experiences outages, this will prevent the clients from multiplying the issue with a flood of reconnect attempts.
- 30+ minute ping wait time is short enough as a user's session is usually around 10 to 15 minutes

increase ping wait timeout to reduce pressure on codemetrics

---

src/command-helper.ts
src/managers/ProgressManager.ts

* The registered updateSettings command was providing the promise result to the "progressIt" instead of the actual function with the array of args. This fixes this issue. Its currently throwing unhandled rejection exceptions but still submitting the settings updates.

update usage of progressIt for the update settings function

---

src/managers/ChangeStateManager.ts
src/websockets.ts

This will reset the websocket connection if the liveness ping reset is twice as old as the last time the ws ping was registered

reset stale websocket connection

---

src/managers/FileManager.ts

After trying to debug the extension, I had the same error mentioned by [morphx666](https://github.com/morphx666) here: [#376 - Extension activation fails with error: RangeError: Maximum call stack size exceeded](https://github.com/swdotcom/swdc-vscode/issues/376#issuecomment-1033196562)
An exception was thrown on `FileManager.getFileDataAsJson()`, trying to parse a file content as a JSON, and that resulted in a loop causing the `RangeError: Maximum call stack size exceeded.`
In my case, the file to parse was `session.json`; the file existed and was successfully read, however the error happened while calling JSON.parse()... After some digging I noticed an `\ufeff` character at the begginning of the file, so by doing a .trim() to the read content, it became parseable.
As an example, my …

Updated FileManager.getFileDataAsJson to trim string prior parsing. (issue #387)
