swdotcom/swdc-vscode

README.md

In order to increase awareness of extensions in the marketplace that include Live Share integration, we created a new `Live Share Enabled` badge (see [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) for example). This PR simply adds the badge to the Code Time readme, so that new users can quickly identify that it augments Live Share (by tracking collaboration time).
Note that we also call out Code Time in our new ["Awesome Live Share" repo](https://aka.ms/vsls-awesome).

Adding the "Live Share Enabled" badge

---

.github/ISSUE_TEMPLATE/bug_report.md

@brettmstevens7 can you please review before I push to master?

Updating with some changes

---

.github/ISSUE_TEMPLATE/config.yml

Changes to github join the community page

---

yarn.lock

Updating packages due to security issues. I did a yarn interactive and verified that all of the packages updated, are backward compatible.

 Updating package versions

---

src/command-helper.ts
src/managers/KpmManager.ts
src/managers/PluginDataManager.ts
src/model/KeystrokeStats.ts
src/model/UIElement.ts
src/model/models.ts
src/tree/KpmProviderManager.ts

Added the repo click event
Removed the call clearStatsForPayloadProcess when sending the batch data files. The PluginDataManager processor should be the only one changing the payload stats
Bundled the time counter steps together
Updated the postData to stagger processing the payload if it's an unfocused window

updated time counter and added repo click event

---

.vscode/launch.json
package.json
src/Util.ts
src/command-helper.ts
src/extension.ts
src/managers/KpmManager.ts
src/managers/PayloadManager.ts
src/managers/PluginDataManager.ts
src/managers/WallClockManager.ts
src/menu/AccountManager.ts
src/model/KeystrokeStats.ts
src/tree/KpmProviderManager.ts

this PR updates the menu items for vscode code time for task: https://www.notion.so/softwaredotcom/Improve-plugin-UX-by-reordering-the-tree-view-menu-f06d1e94c022417d9775eb58ab79879b

ux menu improvements

---

package.json
src/managers/KpmManager.ts
src/managers/PluginDataManager.ts

this cleans up and optimizes the way vscode gets the text change info like lines changed and chars changed

refactor and optimize text change info

---

src/managers/ProgressManager.ts
src/menu/MenuManager.ts
src/menu/ReportManager.ts

shows a notification progress for the report generation
https://www.loom.com/share/6d34b4c16ec045fabfc1ac18b44a2c13

add progress notification when opening reports

---

src/Util.ts
src/http/HttpClient.ts
src/managers/PluginDataManager.ts
src/managers/TrackerManager.ts
src/menu/AccountManager.ts
src/user/OnboardManager.ts

this diff adds the tracker function to compose a code time event and send to the tracker library
it also adds a 15 sec timeout to axios so vscode doesn't throw an exception if the app times out

added logic to track codetime events

---

package.json
src/command-helper.ts
src/extension.ts
src/managers/KpmManager.ts
src/storage/SessionSummaryData.ts
src/tree/KpmProviderManager.ts

this adds tracking for the file scroll and status bar events

scroll and status bar event tracking updates

---

src/managers/TrackerManager.ts
src/menu/AccountManager.ts

general cleanup based on review

---

src/managers/KpmManager.ts

also removing unused code
Creates these events:

adding focus and unfocus tracking.  

---

package.json
src/Util.ts
src/command-helper.ts
src/tree/KpmProviderManager.ts

this adds the button "Log in to existing account"

add existing account login button

---

package.json
yarn.lock

snowplow payload result:
"geo_timezone": "America/Los_Angeles",
"os_timezone": "America/Los_Angeles",

use latest tracker to send os timezone

---

README.md

- added three new images and descriptions from the Code Anywhere dashboard

add dashboard features

---

src/command-helper.ts
src/menu/AccountManager.ts

https://www.loom.com/share/858b6da9758f402883592c2eb721c7d9

fix the labeling to log in with an existing account

---

package.json
resources/dark/options.svg
resources/light/options.svg
src/command-helper.ts
src/managers/OsaScriptManager.ts
src/managers/SlackManager.ts
src/menu/AccountManager.ts
src/menu/ContextMenuManager.ts
src/tree/CodeTimeFlowProvider.ts
src/tree/KpmProvider.ts
src/tree/KpmProviderManager.ts

new stats tree implementation

---

src/DataController.ts
src/Util.ts
src/command-helper.ts
src/managers/SlackManager.ts
src/menu/AccountManager.ts
src/tree/CodeTimeMenuProvider.ts
src/tree/KpmProviderManager.ts
src/user/OnboardManager.ts

add the avg function to show percent of daily averages

---

package.json
src/Constants.ts
src/DataController.ts
src/Util.ts
src/command-helper.ts
src/managers/ConfigManager.ts
src/managers/FlowManager.ts
src/managers/SlackManager.ts
src/model/ConfigSettings.ts
src/model/KeystrokeStats.ts
src/tree/KpmProviderManager.ts

add the code time avg and tooltip and zen config settings model

---

package.json
src/managers/ConfigManager.ts
src/managers/FlowManager.ts
src/model/ConfigSettings.ts
src/tree/KpmProviderManager.ts

use enums to allow the user to pick the screen mode when enabling flow

---

.vscode/launch.json
package.json
src/DataController.ts
src/Util.ts
src/managers/KpmManager.ts
src/managers/TrackerManager.ts
src/model/models.ts
src/repo/GitUtil.ts
yarn.lock

to capture uncommitted changes
Requires https://github.com/swdotcom/swdc-tracker/pull/41 to be in first and update the package.json

adding file save event and emitted a git_event when file saves occur

---

README.md

- new, cleaner visuals that will work on light/dark backgrounds
- removed less helpful visuals and text
- added descriptions of new features in next version

added new visuals and feature descriptions to readme

---

resources/dark/dot-outlined.svg
resources/dark/dot.svg
resources/light/dot-outlined.svg
resources/light/dot.svg
src/command-helper.ts
src/managers/FlowManager.ts
src/managers/ScreenManager.ts
src/managers/SlackManager.ts
src/tree/CodeTimeFlowProvider.ts
src/tree/KpmProviderManager.ts

https://www.loom.com/share/bfe5bea262ca4267828eb21e183db0ea

updated the flow iconand cleaned up the provider flow state

---

src/DataController.ts
src/Util.ts
src/managers/FlowManager.ts
src/managers/SlackManager.ts
src/tree/KpmProviderManager.ts

this disables the flow state correctly if the user changes the screen state and they don't have slack connected

fix flow toggle when slack is not connected

---

src/DataController.ts

when web ui and codemetrics changes go to prod this can rely on auth callback state to match a user

remove email auth fallback and rely on matching by auth callback state

---

package.json
src/DataController.ts
src/Util.ts
src/managers/SlackManager.ts
yarn.lock

clear slack integrations fix

---

src/Util.ts
src/extension.ts
src/http/HttpClient.ts

* send plugin uuid header
* move the initialize plugin to appropriate initialize function

send plugin uuid header

---

src/extension.ts
src/websockets.ts

- This means the server recieved invalid websocket headers

Handle 426 response from /websockets

---

src/DataController.ts
src/events/userEventEmitter.ts
src/notifications/endOfDay.ts

https://www.loom.com/share/c6f0b0e344ff4a6faea2e7a9cf4bafbe

add end of day notification

---

README.md

- Image updates to show new side bar features
- Updated descriptions of onboarding, side bar, Flow Mode, and dashboard

readme changes for sidebar redesign

---

README.md

Swapped out a few PNGs for SVGs in the readme (logo and sign up button) that should avoid scaling issues in the marketplace listing.

swap out readme pngs with svgs

---

src/command-helper.ts
src/tree/TreeButtonProvider.ts

this sends the status bar click event

add the status bar ui interaction event

---

README.md

- new Teams section
- updated instructions to work with UI changes
- other tweaks to wording for clarity

add teams features to readme

---

src/managers/SlackManager.ts

Changing query params to lower case to avoid issues.

features to snake case

---

package.json
src/command-helper.ts
src/managers/SummaryManager.ts
src/message_handlers/current_day_stats_update.ts
src/websockets.ts

this listens to the current_day_stats_update ws event to update the current stats for the plugin

add current day status websocket subscribe handler

---

src/notifications/endOfDay.ts

This will have to wait until the new format is in prod, but this now reads the new format to determine the millis until the report notification should be shown.

handle new work hours format to show end of day report

---

src/websockets.ts

this adds the client ping listener to keep the websocket connection alive or terminate if it hasn't received a ping from the server

client websocket ping listener to keep the connection alive

---

src/Constants.ts
src/DataController.ts
src/app/views/components/orgs.tsx
src/app/views/sidebar.tsx
src/command-helper.ts
src/managers/TeamManager.ts
src/sidebar/ReactData.ts

* Wait to show the CTA to connect GitHub until after registration
* Change messaging and link for connecting GitHub

connect github cta and list of orgs in sidebar

---

src/managers/FlowManager.ts

* This will skip showing the slack connect prompt if the plugin initiates flow mode automatically

prevent showing slack connect prompt for automated flow mode

---

src/Util.ts
src/managers/FlowManager.ts
src/managers/SlackManager.ts
src/managers/WebViewManager.ts

this was showing a popup that slack was not installed when the user is actually not registered. that message is removed in this with the proper checks for auto vs manual flow mode

remove check slack check for flow mode

---

package.json
src/Constants.ts
src/DataController.ts
src/Util.ts
src/command-helper.ts
src/extension.ts
src/managers/ConfigManager.ts
src/managers/FileManager.ts
src/managers/FlowManager.ts
src/managers/ScreenManager.ts
src/managers/SlackManager.ts
src/message_handlers/integration_connection.ts
src/notifications/endOfDay.ts
src/storage/SessionSummaryData.ts
src/user/OnboardManager.ts
yarn.lock

use rails user api and data structure

---

package.json
src/DataController.ts
src/command-helper.ts
src/managers/ConfigManager.ts
src/managers/FlowManager.ts
src/managers/StatusBarManager.ts
src/message_handlers/flow_score.ts
src/notifications/endOfDay.ts

remove flow mode required and act metric for anon

---

src/Util.ts
src/menu/AccountManager.ts
src/user/OnboardManager.ts

* calls the app endpoint for login/register

use app login endpoint and send hash with uuid for plugin uuid

---

README.md

- Clean up descriptions of existing features for accuracy 
- Replace header text with latest updates on GitHub app
- Add descriptions of new team features, including new screenshot
- Add link to new security page

Update readme with GitHub app features

---

README.md

I'm updating the README with more up-to-date information: 
- New screenshots
- Better description of team features
- Link to both GitHub and Bitbucket apps
- Removed/updated instructions

update readme with latest features and screenshots

---

README.md

adding details about what we collect and why

---

src/http/HttpClient.ts
src/sidebar/CodeTimeView.ts

- Clear the JWT when a 401 is returned since the JWT is no longer valid

Handle 401 when making get requests to software-app

---

.vscode/launch.json
package.json
src/Constants.ts
src/http/HttpClient.ts
src/managers/ExtensionManager.ts
src/managers/TrackerManager.ts
src/websockets.ts
yarn.lock

- Update Constants to more easily test against development
- Remove deprecated API URL

Use swdc-tracker v1.6.0
